// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Odonto.Infrastructure.Persistence;

#nullable disable

namespace Odonto.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730192632_Odontograma")]
    partial class Odontograma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Odonto.Domain.Entities.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("OdontologoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<bool>("TodoElDia")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("OdontologoId");

                    b.HasIndex("TenantId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.EventoOdontograma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nota")
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroFdi")
                        .HasColumnType("int");

                    b.Property<Guid?>("OdontologoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Tratamiento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OdontologoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("PacienteId", "NumeroFdi", "Fecha");

                    b.ToTable("EventosOdontograma");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Notificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<bool>("Enviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaEnvioProgramada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaEnvioReal")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TipoRecordatorio")
                        .HasColumnType("int");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.HasIndex("Enviado", "FechaEnvioProgramada");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Odontologo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ColorAgenda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Especialidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Odontologos");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Dni")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("OdontologoPrincipalId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OdontologoPrincipalId");

                    b.HasIndex("TenantId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MercadoPagoPreapprovalId")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.TipoTratamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TiposTratamiento");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OdontologoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TipoTratamientoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TipoTratamientoId");

                    b.HasIndex("OdontologoId", "FechaHora");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Disponibilidad", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("OdontologoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odontologo");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.EventoOdontograma", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("OdontologoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Odonto.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Odontologo", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Odontologo", "OdontologoPrincipal")
                        .WithMany()
                        .HasForeignKey("OdontologoPrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Pacientes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OdontologoPrincipal");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.TipoTratamiento", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Turno", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("OdontologoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Odonto.Domain.Entities.TipoTratamiento", "TipoTratamiento")
                        .WithMany()
                        .HasForeignKey("TipoTratamientoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");

                    b.Navigation("Tenant");

                    b.Navigation("TipoTratamiento");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Odonto.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Odonto.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Pacientes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
